version: '3'
services:
  web:
    image: nginx:latest
    ports:
      - 8078:80
    volumes:
      - ./src:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
      - db

  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 9018:9000
    volumes:
      - ./src:/var/www/html
    depends_on:
      - db

  db:
    image: mysql:latest
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_USER: laraveluser
      MYSQL_PASSWORD: your_mysql_password
      MYSQL_ROOT_PASSWORD: your_mysql_root_password
    volumes:
      - ./mysql:/var/lib/mysql

